function runTimer(x){
currTime = 50;
    var timeout = 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() {
        x.innerHTML = currTime;
        currTime = currTime - 5;
        
    }, timeout);
    timeout = timeout + 5000;

    setTimeout(function() { alert("Blastoff!"); }, timeout);
}
